### ISSUE TITLE
Model weights sharing and training stopping criterion

### ISSUE THREAD

**Issue by zcwang0702** [EagleW/PaperRobot#17]
Thanks for your great work! 

- Given that model training on both tasks are pretty slow, is it possible for you to share the trained model weights? Especially for the link prediction model.

- I would like to know how do you determine when to stop the model training on each of the task? How many epochs did you use to achieve the best performance?

Looking forward to your reply. Thanks!

**Comment by EagleW** [comment]
@zcwang0702 Thank you very much for your interest in our work!  Due to transition, I have lost all the trained model weight. However, the preferred trained parameters are already included in the code. I stop training based on the num of epochs and early stop patience.  I didn't remember the exact epochs for training. However, the link prediction takes a week on the v100. Paper writing takes one day for training. Feel free to ask me any other questions.

**Comment by zcwang0702** [comment]
Hi Qingyun,

Thanks for your quick reply!
As the paper writing task depends on the link prediction task. Could you please give me some suggestions on how to determine when to stop the model training? For example, what is your empirical range of train/test loss for the link prediction model that is good enough to support paper writing training? Or you just trained the model for 100 epochs and selected the best one?

Best
Zichen

**Comment by EagleW** [comment]
@zcwang0702 Hi, I just wait until the model stop. It will automatically select one with best dev score. The link prediction model usually run about 60-70 epochs. If you want to use the link prediction results for paper generation training, you can directly download the [PubMed Term, Abstract, Conclusion, Title Dataset](https://drive.google.com/open?id=1O91gX2maPHdIRUb9DdZmUOI5issRMXMY) which already include the prediction results. Thanks!
