### ISSUE TITLE
"networkx.exception.NetworkXError: Node 13593 in nodelist is not in G"

### ISSUE THREAD

**Issue by gitfans5** [EagleW/PaperRobot#20]
How to fix the error "networkx.exception.NetworkXError: Node 13593 in nodelist is not in G"? Thanks!

**Comment by EagleW** [comment]
![image](https://user-images.githubusercontent.com/14304965/153326150-b85107d5-1cf9-4120-8ade-1db1412ea225.png)
I redownload the code and data. I try to rerun it on the server but didn't find any problem Did you change any part of the code?

**Comment by 1754699523** [comment]
> 你能和我分享你的截图吗？

<img width="903" alt="image" src="https://user-images.githubusercontent.com/66351840/189574633-5ab3e072-4490-43c7-974e-f931ec527c9c.png">

**Comment by ZuoHaoyu** [comment]
Hi there, please downgrade the networkx to a version with 2.3. In this version, it won't confirm the nodelist and graph.

**Comment by William-LWY** [comment]
![image](https://user-images.githubusercontent.com/93751196/209774526-0d022259-7cf8-4017-a161-5c5ef5fbee97.png)
Hi，how to solve this problem?  networkx is 2.8.8, python is 3.9. 
Maybe the issue comes from pygraphviz.

**Comment by EagleW** [comment]
@William-LWY Please downgrade your networkx

**Comment by ZuoHaoyu** [comment]
@William-LWY Hi you can downgrade networkx to version 2.3 and that would be solved.

I'm just leaving another issue here when running train.py after this to see if you happened to encounter on this:

RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([50, 64]), input2: torch.Size([50, 64]), target: torch.Size([1]) 

I'm using the original data and code. I'm not sure if it's only my problem because this issue is not proposed before.
